# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/puhaty/Dupex Data/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/puhaty/Dupex Data/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/puhaty/Dupex Data/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy/CMakeFiles" "/media/puhaty/Dupex Data/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/puhaty/Dupex Data/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named bike_shop

# Build rule for target.
bike_shop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bike_shop
.PHONY : bike_shop

# fast build rule for target.
bike_shop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/build
.PHONY : bike_shop/fast

core/basket.o: core/basket.cpp.o

.PHONY : core/basket.o

# target to build an object file
core/basket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/basket.cpp.o
.PHONY : core/basket.cpp.o

core/basket.i: core/basket.cpp.i

.PHONY : core/basket.i

# target to preprocess a source file
core/basket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/basket.cpp.i
.PHONY : core/basket.cpp.i

core/basket.s: core/basket.cpp.s

.PHONY : core/basket.s

# target to generate assembly for a file
core/basket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/basket.cpp.s
.PHONY : core/basket.cpp.s

core/bike.o: core/bike.cpp.o

.PHONY : core/bike.o

# target to build an object file
core/bike.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/bike.cpp.o
.PHONY : core/bike.cpp.o

core/bike.i: core/bike.cpp.i

.PHONY : core/bike.i

# target to preprocess a source file
core/bike.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/bike.cpp.i
.PHONY : core/bike.cpp.i

core/bike.s: core/bike.cpp.s

.PHONY : core/bike.s

# target to generate assembly for a file
core/bike.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/bike.cpp.s
.PHONY : core/bike.cpp.s

core/front_shock.o: core/front_shock.cpp.o

.PHONY : core/front_shock.o

# target to build an object file
core/front_shock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/front_shock.cpp.o
.PHONY : core/front_shock.cpp.o

core/front_shock.i: core/front_shock.cpp.i

.PHONY : core/front_shock.i

# target to preprocess a source file
core/front_shock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/front_shock.cpp.i
.PHONY : core/front_shock.cpp.i

core/front_shock.s: core/front_shock.cpp.s

.PHONY : core/front_shock.s

# target to generate assembly for a file
core/front_shock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/front_shock.cpp.s
.PHONY : core/front_shock.cpp.s

core/headset.o: core/headset.cpp.o

.PHONY : core/headset.o

# target to build an object file
core/headset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/headset.cpp.o
.PHONY : core/headset.cpp.o

core/headset.i: core/headset.cpp.i

.PHONY : core/headset.i

# target to preprocess a source file
core/headset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/headset.cpp.i
.PHONY : core/headset.cpp.i

core/headset.s: core/headset.cpp.s

.PHONY : core/headset.s

# target to generate assembly for a file
core/headset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/headset.cpp.s
.PHONY : core/headset.cpp.s

core/receipt.o: core/receipt.cpp.o

.PHONY : core/receipt.o

# target to build an object file
core/receipt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/receipt.cpp.o
.PHONY : core/receipt.cpp.o

core/receipt.i: core/receipt.cpp.i

.PHONY : core/receipt.i

# target to preprocess a source file
core/receipt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/receipt.cpp.i
.PHONY : core/receipt.cpp.i

core/receipt.s: core/receipt.cpp.s

.PHONY : core/receipt.s

# target to generate assembly for a file
core/receipt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/receipt.cpp.s
.PHONY : core/receipt.cpp.s

core/shop.o: core/shop.cpp.o

.PHONY : core/shop.o

# target to build an object file
core/shop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/shop.cpp.o
.PHONY : core/shop.cpp.o

core/shop.i: core/shop.cpp.i

.PHONY : core/shop.i

# target to preprocess a source file
core/shop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/shop.cpp.i
.PHONY : core/shop.cpp.i

core/shop.s: core/shop.cpp.s

.PHONY : core/shop.s

# target to generate assembly for a file
core/shop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/shop.cpp.s
.PHONY : core/shop.cpp.s

core/warehouse.o: core/warehouse.cpp.o

.PHONY : core/warehouse.o

# target to build an object file
core/warehouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/warehouse.cpp.o
.PHONY : core/warehouse.cpp.o

core/warehouse.i: core/warehouse.cpp.i

.PHONY : core/warehouse.i

# target to preprocess a source file
core/warehouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/warehouse.cpp.i
.PHONY : core/warehouse.cpp.i

core/warehouse.s: core/warehouse.cpp.s

.PHONY : core/warehouse.s

# target to generate assembly for a file
core/warehouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/core/warehouse.cpp.s
.PHONY : core/warehouse.cpp.s

main_tui.o: main_tui.cpp.o

.PHONY : main_tui.o

# target to build an object file
main_tui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/main_tui.cpp.o
.PHONY : main_tui.cpp.o

main_tui.i: main_tui.cpp.i

.PHONY : main_tui.i

# target to preprocess a source file
main_tui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/main_tui.cpp.i
.PHONY : main_tui.cpp.i

main_tui.s: main_tui.cpp.s

.PHONY : main_tui.s

# target to generate assembly for a file
main_tui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/main_tui.cpp.s
.PHONY : main_tui.cpp.s

tui/basket_presenter.o: tui/basket_presenter.cpp.o

.PHONY : tui/basket_presenter.o

# target to build an object file
tui/basket_presenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/basket_presenter.cpp.o
.PHONY : tui/basket_presenter.cpp.o

tui/basket_presenter.i: tui/basket_presenter.cpp.i

.PHONY : tui/basket_presenter.i

# target to preprocess a source file
tui/basket_presenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/basket_presenter.cpp.i
.PHONY : tui/basket_presenter.cpp.i

tui/basket_presenter.s: tui/basket_presenter.cpp.s

.PHONY : tui/basket_presenter.s

# target to generate assembly for a file
tui/basket_presenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/basket_presenter.cpp.s
.PHONY : tui/basket_presenter.cpp.s

tui/bike_presenter.o: tui/bike_presenter.cpp.o

.PHONY : tui/bike_presenter.o

# target to build an object file
tui/bike_presenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/bike_presenter.cpp.o
.PHONY : tui/bike_presenter.cpp.o

tui/bike_presenter.i: tui/bike_presenter.cpp.i

.PHONY : tui/bike_presenter.i

# target to preprocess a source file
tui/bike_presenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/bike_presenter.cpp.i
.PHONY : tui/bike_presenter.cpp.i

tui/bike_presenter.s: tui/bike_presenter.cpp.s

.PHONY : tui/bike_presenter.s

# target to generate assembly for a file
tui/bike_presenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/bike_presenter.cpp.s
.PHONY : tui/bike_presenter.cpp.s

tui/front_shock_presenter.o: tui/front_shock_presenter.cpp.o

.PHONY : tui/front_shock_presenter.o

# target to build an object file
tui/front_shock_presenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/front_shock_presenter.cpp.o
.PHONY : tui/front_shock_presenter.cpp.o

tui/front_shock_presenter.i: tui/front_shock_presenter.cpp.i

.PHONY : tui/front_shock_presenter.i

# target to preprocess a source file
tui/front_shock_presenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/front_shock_presenter.cpp.i
.PHONY : tui/front_shock_presenter.cpp.i

tui/front_shock_presenter.s: tui/front_shock_presenter.cpp.s

.PHONY : tui/front_shock_presenter.s

# target to generate assembly for a file
tui/front_shock_presenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/front_shock_presenter.cpp.s
.PHONY : tui/front_shock_presenter.cpp.s

tui/headset_presenter.o: tui/headset_presenter.cpp.o

.PHONY : tui/headset_presenter.o

# target to build an object file
tui/headset_presenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/headset_presenter.cpp.o
.PHONY : tui/headset_presenter.cpp.o

tui/headset_presenter.i: tui/headset_presenter.cpp.i

.PHONY : tui/headset_presenter.i

# target to preprocess a source file
tui/headset_presenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/headset_presenter.cpp.i
.PHONY : tui/headset_presenter.cpp.i

tui/headset_presenter.s: tui/headset_presenter.cpp.s

.PHONY : tui/headset_presenter.s

# target to generate assembly for a file
tui/headset_presenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/headset_presenter.cpp.s
.PHONY : tui/headset_presenter.cpp.s

tui/manager.o: tui/manager.cpp.o

.PHONY : tui/manager.o

# target to build an object file
tui/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/manager.cpp.o
.PHONY : tui/manager.cpp.o

tui/manager.i: tui/manager.cpp.i

.PHONY : tui/manager.i

# target to preprocess a source file
tui/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/manager.cpp.i
.PHONY : tui/manager.cpp.i

tui/manager.s: tui/manager.cpp.s

.PHONY : tui/manager.s

# target to generate assembly for a file
tui/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/manager.cpp.s
.PHONY : tui/manager.cpp.s

tui/warehouse_presenter.o: tui/warehouse_presenter.cpp.o

.PHONY : tui/warehouse_presenter.o

# target to build an object file
tui/warehouse_presenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/warehouse_presenter.cpp.o
.PHONY : tui/warehouse_presenter.cpp.o

tui/warehouse_presenter.i: tui/warehouse_presenter.cpp.i

.PHONY : tui/warehouse_presenter.i

# target to preprocess a source file
tui/warehouse_presenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/warehouse_presenter.cpp.i
.PHONY : tui/warehouse_presenter.cpp.i

tui/warehouse_presenter.s: tui/warehouse_presenter.cpp.s

.PHONY : tui/warehouse_presenter.s

# target to generate assembly for a file
tui/warehouse_presenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bike_shop.dir/build.make CMakeFiles/bike_shop.dir/tui/warehouse_presenter.cpp.s
.PHONY : tui/warehouse_presenter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... bike_shop"
	@echo "... core/basket.o"
	@echo "... core/basket.i"
	@echo "... core/basket.s"
	@echo "... core/bike.o"
	@echo "... core/bike.i"
	@echo "... core/bike.s"
	@echo "... core/front_shock.o"
	@echo "... core/front_shock.i"
	@echo "... core/front_shock.s"
	@echo "... core/headset.o"
	@echo "... core/headset.i"
	@echo "... core/headset.s"
	@echo "... core/receipt.o"
	@echo "... core/receipt.i"
	@echo "... core/receipt.s"
	@echo "... core/shop.o"
	@echo "... core/shop.i"
	@echo "... core/shop.s"
	@echo "... core/warehouse.o"
	@echo "... core/warehouse.i"
	@echo "... core/warehouse.s"
	@echo "... main_tui.o"
	@echo "... main_tui.i"
	@echo "... main_tui.s"
	@echo "... tui/basket_presenter.o"
	@echo "... tui/basket_presenter.i"
	@echo "... tui/basket_presenter.s"
	@echo "... tui/bike_presenter.o"
	@echo "... tui/bike_presenter.i"
	@echo "... tui/bike_presenter.s"
	@echo "... tui/front_shock_presenter.o"
	@echo "... tui/front_shock_presenter.i"
	@echo "... tui/front_shock_presenter.s"
	@echo "... tui/headset_presenter.o"
	@echo "... tui/headset_presenter.i"
	@echo "... tui/headset_presenter.s"
	@echo "... tui/manager.o"
	@echo "... tui/manager.i"
	@echo "... tui/manager.s"
	@echo "... tui/warehouse_presenter.o"
	@echo "... tui/warehouse_presenter.i"
	@echo "... tui/warehouse_presenter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

