# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy/CMakeFiles /mnt/d/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/programowanie/C++/object/studia/projekt_II/sklep_rowerowy/proe2020l_gr_103_sklep_rowerowy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named obj

# Build rule for target.
obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj
.PHONY : obj

# fast build rule for target.
obj/fast:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/build
.PHONY : obj/fast

#=============================================================================
# Target rules for targets named bike_shope.exe

# Build rule for target.
bike_shope.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bike_shope.exe
.PHONY : bike_shope.exe

# fast build rule for target.
bike_shope.exe/fast:
	$(MAKE) -f CMakeFiles/bike_shope.exe.dir/build.make CMakeFiles/bike_shope.exe.dir/build
.PHONY : bike_shope.exe/fast

src/basket.o: src/basket.cpp.o

.PHONY : src/basket.o

# target to build an object file
src/basket.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/basket.cpp.o
.PHONY : src/basket.cpp.o

src/basket.i: src/basket.cpp.i

.PHONY : src/basket.i

# target to preprocess a source file
src/basket.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/basket.cpp.i
.PHONY : src/basket.cpp.i

src/basket.s: src/basket.cpp.s

.PHONY : src/basket.s

# target to generate assembly for a file
src/basket.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/basket.cpp.s
.PHONY : src/basket.cpp.s

src/bike.o: src/bike.cpp.o

.PHONY : src/bike.o

# target to build an object file
src/bike.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/bike.cpp.o
.PHONY : src/bike.cpp.o

src/bike.i: src/bike.cpp.i

.PHONY : src/bike.i

# target to preprocess a source file
src/bike.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/bike.cpp.i
.PHONY : src/bike.cpp.i

src/bike.s: src/bike.cpp.s

.PHONY : src/bike.s

# target to generate assembly for a file
src/bike.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/bike.cpp.s
.PHONY : src/bike.cpp.s

src/front_shock.o: src/front_shock.cpp.o

.PHONY : src/front_shock.o

# target to build an object file
src/front_shock.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/front_shock.cpp.o
.PHONY : src/front_shock.cpp.o

src/front_shock.i: src/front_shock.cpp.i

.PHONY : src/front_shock.i

# target to preprocess a source file
src/front_shock.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/front_shock.cpp.i
.PHONY : src/front_shock.cpp.i

src/front_shock.s: src/front_shock.cpp.s

.PHONY : src/front_shock.s

# target to generate assembly for a file
src/front_shock.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/front_shock.cpp.s
.PHONY : src/front_shock.cpp.s

src/headset.o: src/headset.cpp.o

.PHONY : src/headset.o

# target to build an object file
src/headset.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/headset.cpp.o
.PHONY : src/headset.cpp.o

src/headset.i: src/headset.cpp.i

.PHONY : src/headset.i

# target to preprocess a source file
src/headset.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/headset.cpp.i
.PHONY : src/headset.cpp.i

src/headset.s: src/headset.cpp.s

.PHONY : src/headset.s

# target to generate assembly for a file
src/headset.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/headset.cpp.s
.PHONY : src/headset.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/manager.o: src/manager.cpp.o

.PHONY : src/manager.o

# target to build an object file
src/manager.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/manager.cpp.o
.PHONY : src/manager.cpp.o

src/manager.i: src/manager.cpp.i

.PHONY : src/manager.i

# target to preprocess a source file
src/manager.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/manager.cpp.i
.PHONY : src/manager.cpp.i

src/manager.s: src/manager.cpp.s

.PHONY : src/manager.s

# target to generate assembly for a file
src/manager.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/manager.cpp.s
.PHONY : src/manager.cpp.s

src/receipt.o: src/receipt.cpp.o

.PHONY : src/receipt.o

# target to build an object file
src/receipt.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/receipt.cpp.o
.PHONY : src/receipt.cpp.o

src/receipt.i: src/receipt.cpp.i

.PHONY : src/receipt.i

# target to preprocess a source file
src/receipt.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/receipt.cpp.i
.PHONY : src/receipt.cpp.i

src/receipt.s: src/receipt.cpp.s

.PHONY : src/receipt.s

# target to generate assembly for a file
src/receipt.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/receipt.cpp.s
.PHONY : src/receipt.cpp.s

src/shop.o: src/shop.cpp.o

.PHONY : src/shop.o

# target to build an object file
src/shop.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shop.cpp.o
.PHONY : src/shop.cpp.o

src/shop.i: src/shop.cpp.i

.PHONY : src/shop.i

# target to preprocess a source file
src/shop.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shop.cpp.i
.PHONY : src/shop.cpp.i

src/shop.s: src/shop.cpp.s

.PHONY : src/shop.s

# target to generate assembly for a file
src/shop.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/shop.cpp.s
.PHONY : src/shop.cpp.s

src/warehouse.o: src/warehouse.cpp.o

.PHONY : src/warehouse.o

# target to build an object file
src/warehouse.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/warehouse.cpp.o
.PHONY : src/warehouse.cpp.o

src/warehouse.i: src/warehouse.cpp.i

.PHONY : src/warehouse.i

# target to preprocess a source file
src/warehouse.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/warehouse.cpp.i
.PHONY : src/warehouse.cpp.i

src/warehouse.s: src/warehouse.cpp.s

.PHONY : src/warehouse.s

# target to generate assembly for a file
src/warehouse.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/warehouse.cpp.s
.PHONY : src/warehouse.cpp.s

src/warehouse_presenter.o: src/warehouse_presenter.cpp.o

.PHONY : src/warehouse_presenter.o

# target to build an object file
src/warehouse_presenter.cpp.o:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/warehouse_presenter.cpp.o
.PHONY : src/warehouse_presenter.cpp.o

src/warehouse_presenter.i: src/warehouse_presenter.cpp.i

.PHONY : src/warehouse_presenter.i

# target to preprocess a source file
src/warehouse_presenter.cpp.i:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/warehouse_presenter.cpp.i
.PHONY : src/warehouse_presenter.cpp.i

src/warehouse_presenter.s: src/warehouse_presenter.cpp.s

.PHONY : src/warehouse_presenter.s

# target to generate assembly for a file
src/warehouse_presenter.cpp.s:
	$(MAKE) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/src/warehouse_presenter.cpp.s
.PHONY : src/warehouse_presenter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... obj"
	@echo "... bike_shope.exe"
	@echo "... src/basket.o"
	@echo "... src/basket.i"
	@echo "... src/basket.s"
	@echo "... src/bike.o"
	@echo "... src/bike.i"
	@echo "... src/bike.s"
	@echo "... src/front_shock.o"
	@echo "... src/front_shock.i"
	@echo "... src/front_shock.s"
	@echo "... src/headset.o"
	@echo "... src/headset.i"
	@echo "... src/headset.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/manager.o"
	@echo "... src/manager.i"
	@echo "... src/manager.s"
	@echo "... src/receipt.o"
	@echo "... src/receipt.i"
	@echo "... src/receipt.s"
	@echo "... src/shop.o"
	@echo "... src/shop.i"
	@echo "... src/shop.s"
	@echo "... src/warehouse.o"
	@echo "... src/warehouse.i"
	@echo "... src/warehouse.s"
	@echo "... src/warehouse_presenter.o"
	@echo "... src/warehouse_presenter.i"
	@echo "... src/warehouse_presenter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

